version: '3'
services:
  reserva-app:
    restart: always
    container_name: reserva_app
    build:
      context: ./reservasApplication
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-reserva:5432/reservasdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SERVER_PORT=8082
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8082:8082"
    depends_on:
      - db-reserva
      - rabbitmq
    networks:
      - net-reserva

  sala-app:
    restart: always
    container_name: sala_app
    build:
      context: ./salaApplication
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-sala:5432/saladb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SERVER_PORT=8083
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8083:8083"
    depends_on:
      - db-sala
      - rabbitmq
    networks:
      - net-sala

  user-app:
    restart: always
    container_name: user_app
    build:
      context: ./userApplication
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-user:5432/userdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SERVER_PORT=8085
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8085:8085"
    depends_on:
      - db-user
      - rabbitmq
    networks:
      - net-user

  db-reserva:
    image: postgres:latest
    restart: always
    container_name: reservasdb
    environment:
      POSTGRES_DB: reservasdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - net-reserva

  db-user:
    image: postgres:latest
    restart: always
    container_name: userdb
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    networks:
      - net-user

  db-sala:
    image: postgres:latest
    restart: always
    container_name: saladb
    environment:
      POSTGRES_DB: saladb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    networks:
      - net-sala

  adminer:
    container_name: adminer
    restart: always
    image: adminer:latest
    ports:
      - "8081:8080"
    networks:
      - net-sala
      - net-user
      - net-reserva

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - net-sala
      - net-user
      - net-reserva
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      
  eureka-server:
    build:
      context: ./eurekaServer
      dockerfile: Dockerfile
    container_name: eureka_server
    ports:
      - "8761:8761"
    networks:
      - net-sala
      - net-user
      - net-reserva

  gateway-app:
    build:
      context: ./gatewayApplication
      dockerfile: Dockerfile
    container_name: gateway_app
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server
      - user-app
      - sala-app
      - reserva-app
    networks:
      - net-sala
      - net-user
      - net-reserva

networks:
  net-sala:
    driver: bridge
  net-user:
    driver: bridge
  net-reserva:
    driver: bridge
