version: '3'
services:
  reserva-app:
    restart: always
    container_name: reserva_app
    build:
      context: ./application
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-reserva:5432/reservasdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SERVER_PORT=8082
    ports:
      - "8082:8082"
    depends_on:
      - db-reserva
    networks:
      - net

  sala-app:
    restart: always
    container_name: sala_app
    build:
      context: ./salaApplication
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-sala:5432/saladb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SERVER_PORT=8083 
    ports:
      - "8083:8083"
    depends_on:
      - db-sala
    networks:
      - net

  user-app:
    restart: always
    container_name: user_app
    build:
      context: ./userApplication
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-user:5432/userdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SERVER_PORT=8085
    ports:
      - "8085:8085"
    depends_on:
      - db-user
    networks:
      - net

  db-reserva:
    image: postgres:latest
    restart: always
    container_name: reservasdb
    environment:
      POSTGRES_DB: reservasdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - net

  db-user:
    image: postgres:latest
    restart: always
    container_name: userdb
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    networks:
      - net

  db-sala:
    image: postgres:latest
    restart: always
    container_name: saladb
    environment:
      POSTGRES_DB: saladb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    networks:
      - net    

  adminer:
    container_name: adminer
    restart: always
    image: adminer:latest
    ports:
      - "8081:8080"
    networks:
      - net

networks:
  net:
    driver: bridge
