FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/*.jar /app/gateway.jar
EXPOSE 8090
ENTRYPOINT ["java", "-jar", "gateway.jar"]